create table if not exists ability
(
    ability_id   bigint generated by default as identity
        primary key,
    created_at   timestamp,
    modified_at  timestamp,
    ability_type varchar(10),
    name         varchar(30)
);

create table if not exists users
(
    user_id     bigint generated by default as identity
        primary key,
    created_at  timestamp,
    modified_at timestamp,
    email       varchar(50),
    nickname    varchar(20),
    social_type varchar(10)
);

create table if not exists project
(
    project_id  bigint generated by default as identity
        primary key,
    created_at  timestamp,
    modified_at timestamp,
    title       varchar(30),
    user_id     bigint,
    foreign key (user_id) references users(user_id) on delete cascade,
);

create table if not exists work
(
    work_id     bigint generated by default as identity
        primary key,
    created_at  timestamp,
    modified_at timestamp,
    date        timestamp,
    description text,
    title       varchar(60),
    project_id  bigint,
    foreign key (project_id) references project(project_id) on delete cascade,
);

create table work_ability
(
    work_ability_id bigint generated by default as identity
        primary key,
    created_at      timestamp,
    modified_at     timestamp,
    ability_id      bigint,
    work_id         bigint,
    foreign key (ability_id) references ability(ability_id) on delete cascade,
    foreign key (work_id) references work(work_id) on delete cascade,
);
